package watchdog

import (
	"fmt"
	"sort"
	"strings"

	"github.com/jahwag/clem/internal/config"
	"github.com/jahwag/clem/internal/coordination"
	"github.com/jahwag/clem/internal/proxy"
)

const watchdogScript = `#!/bin/bash
# clem-watchdog-{{.Project}}.sh — generated by clem provision
# Monitors agents for {{.Project}} and restarts dead sessions.

PROJECT="{{.Project}}"
COOLDOWN_DIR="/tmp/clem-watchdog-{{.Project}}"
COOLDOWN_SECONDS=300

mkdir -p "$COOLDOWN_DIR"

# Chat backend token sourced from orchestrator agent's .env
{{.EnvSource}}

send_alert() {
    local msg="$1"
    local safe_msg
    safe_msg=$(python3 -c "import json,sys; print(json.dumps(sys.argv[1])[1:-1])" "$msg" 2>/dev/null) || safe_msg=$msg
    if [ -n "${{.TokenEnvVar}}" ] && [ -n "{{.AlertChannel}}" ]; then
        {{.AlertCurl}}
    fi
    echo "$(date -Iseconds) ALERT: $msg"
}

check_agent() {
    local agent_key="$1"
    local os_user="$2"
    local service="$3"
    local stale_threshold="$4"
    local cooldown_file="$COOLDOWN_DIR/${agent_key}.cooldown"

    # Check cooldown
    if [ -f "$cooldown_file" ]; then
        local last_alert
        last_alert=$(cat "$cooldown_file")
        local now
        now=$(date +%s)
        if (( now - last_alert < COOLDOWN_SECONDS )); then
            return
        fi
    fi

    local systemd_state
    systemd_state=$(systemctl show -p ActiveState --value "$service" 2>/dev/null)

    local tmux_alive="no"
    tmux has-session -t "$agent_key" 2>/dev/null && tmux_alive="yes"

    local fail_count_file="$COOLDOWN_DIR/${agent_key}.fails"

    # Case 1: systemd service dead — restart, then re-check. Only alert when
    # the restart did NOT bring the service back. Silences noise from
    # transient non-active states (e.g. ExecStop kill-session exit 1 during
    # a clean restart) that historically fired spurious "failed 3 times"
    # alerts even though auto-recovery had succeeded.
    if [ "$systemd_state" != "active" ]; then
        echo "$(date -Iseconds) $agent_key: systemd=$systemd_state — restarting"
        systemctl restart "$service"

        # systemctl restart returns after the job completes, but the forked
        # tmux daemon needs a beat to register its session.
        sleep 3
        local post_state post_tmux
        post_state=$(systemctl show -p ActiveState --value "$service" 2>/dev/null)
        post_tmux="no"
        tmux has-session -t "$agent_key" 2>/dev/null && post_tmux="yes"

        if [ "$post_state" = "active" ] && [ "$post_tmux" = "yes" ]; then
            # Restart succeeded — reset counter, suppress alert.
            echo 0 > "$fail_count_file"
            date +%s > "$cooldown_file"
            return
        fi

        local fails=$(( $(cat "$fail_count_file" 2>/dev/null || echo 0) + 1 ))
        echo "$fails" > "$fail_count_file"
        if (( fails >= 3 )); then
            send_alert "🔴 clem/$PROJECT: $agent_key failed $fails times consecutively (systemd=$post_state tmux=$post_tmux)"
            echo 0 > "$fail_count_file"
        fi
        date +%s > "$cooldown_file"
        return
    fi

    # Case 2: stale agent — runner log hasn't been touched in longer than
    # the agent's own sleep interval (plus a small margin). The per-agent
    # threshold is computed at provision time from iteration_duration so
    # long-iteration configs don't trip on a normal between-iteration sleep.
    local logfile="/home/${os_user}/.claude/${agent_key}-runner.log"
    if [ -f "$logfile" ]; then
        local log_age
        log_age=$(( $(date +%s) - $(stat -c %Y "$logfile") ))
        if (( log_age > stale_threshold )); then
            echo "$(date -Iseconds) $agent_key: stale for $((log_age/60))min — hard restarting"
            pkill -u "$os_user" -f claude || true
            sleep 2
            systemctl restart "$service"
            local fails=$(( $(cat "$fail_count_file" 2>/dev/null || echo 0) + 1 ))
            echo "$fails" > "$fail_count_file"
            if (( fails >= 3 )); then
                send_alert "🔴 clem/$PROJECT: $agent_key stale $fails times consecutively — may be rate-limited or broken"
                echo 0 > "$fail_count_file"
            fi
            date +%s > "$cooldown_file"
            return
        fi
    fi

    # Agent is healthy — reset fail counter
    [ -f "$fail_count_file" ] && echo 0 > "$fail_count_file"
}

check_oom() {
    local marker="$COOLDOWN_DIR/oom.last"
    local since new_ts
    new_ts=$(date +%s)
    if [ -f "$marker" ]; then
        since="@$(cat "$marker")"
    else
        since="5 minutes ago"
    fi

    local hits
    hits=$(journalctl --since "$since" --no-pager 2>/dev/null \
        | grep -E "killed by the OOM killer" \
        | grep -oE "clem-[a-zA-Z0-9_-]+\.service" \
        | sort | uniq -c | awk '{printf "%s x%s\n", $2, $1}')
    if [ -n "$hits" ]; then
        local mem
        mem=$(free -h | awk '/^Mem:/ {printf "%s/%s", $3, $2} /^Swap:/ {printf " swap=%s/%s", $3, $2}')
        send_alert "🔥 clem/$PROJECT OOM-kill detected (last 5min): $hits — RAM $mem"
    fi
    echo "$new_ts" > "$marker"
}
# Transcript prune (daily): agent session JSONLs grow unbounded (~1.5 GB per
# agent-month observed in production). Deletes session transcripts and their
# UUID-named sidecar dirs older than 30 days. The memory/ dir and any other
# non-UUID dir at the same depth are deliberately not matched.
prune_transcripts() {
    local stamp="$COOLDOWN_DIR/transcript-prune.last"
    if [ -f "$stamp" ] && [ $(( $(date +%s) - $(stat -c %Y "$stamp") )) -lt 86400 ]; then
        return
    fi
    local home
    for home in {{.AgentHomes}}; do
        local proj="$home/.claude/projects"
        [ -d "$proj" ] || continue
        find "$proj" -mindepth 2 -maxdepth 2 -type f -name "*.jsonl" -mtime +30 -delete 2>/dev/null
        find "$proj" -mindepth 2 -maxdepth 2 -type d -regextype posix-extended \
            -regex '.*/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}' \
            -mtime +30 -exec rm -rf {} + 2>/dev/null
    done
    touch "$stamp"
}
{{.EgressCheckDef}}{{.VaultCheckDef}}
{{.AgentChecks}}

check_oom
prune_transcripts
{{.EgressInvoke}}{{.VaultInvoke}}`

// egressCheckDef is injected when egress containment is enabled. It tails the
// signed pipelock audit JSONL by line position (robust to rotation, needs no
// jq) and routes blocked/DLP egress events through the existing send_alert.
// The watchdog runs as root, so its alert curl bypasses the agent egress
// firewall — an exfil block cannot also suppress its own alert. Only counts
// and destination hosts are emitted (pipelock already redacts secrets).
//
// NOTE: the verdict/host field names below are matched tolerantly across
// pipelock's likely schema; confirm against a live audit line and tighten.
const egressCheckDef = `
check_egress() {
    local audit="{{.AuditLogPath}}"
    [ -f "$audit" ] || return
    local marker="$COOLDOWN_DIR/egress.pos"
    local last_pos=0
    [ -f "$marker" ] && last_pos=$(cat "$marker")
    local total
    total=$(wc -l < "$audit" 2>/dev/null || echo 0)
    # Log rotated/truncated since last run — restart from the top.
    if (( last_pos > total )); then last_pos=0; fi
    if (( total > last_pos )); then
        local new
        new=$(tail -n +$((last_pos + 1)) "$audit" 2>/dev/null)
        local blocked
        blocked=$(printf '%s\n' "$new" | grep -Ec '"(action|decision|verdict)":[[:space:]]*"(block|blocked|deny|denied)"|"dlp"|"blocked":[[:space:]]*true' || true)
        if (( blocked > 0 )); then
            local dests
            # Only emit bare hostnames (host/sni) — never url/destination, which
            # can carry a query string with a secret (e.g. ?token=...) and would
            # otherwise be exfiltrated verbatim into the chat backend by send_alert.
            dests=$(printf '%s\n' "$new" \
                | grep -oE '"(host|sni)":[[:space:]]*"[^"]+"' \
                | sed -E 's/.*:[[:space:]]*"//; s/"$//' | sort -u | head -5 | tr '\n' ' ')
            send_alert "🛑 clem/$PROJECT egress: $blocked blocked/DLP event(s) — $dests"
        fi
    fi
    echo "$total" > "$marker"
}
`

// vaultCheckDef is injected when the agent-vault credential proxy is active. It
// is a single point of failure for ALL brokered agents' auth, so the watchdog
// probes both systemd liveness and the HTTP health endpoint, restarts on
// failure, and alerts only if the restart did not recover it. Runs as root, so
// the alert curl bypasses the agent egress firewall.
const vaultCheckDef = `
check_agent_vault() {
    local svc="{{.VaultService}}"
    local url="{{.VaultHealthURL}}"
    local state healthy
    state=$(systemctl is-active "$svc" 2>/dev/null)
    healthy=no; curl -fsS --max-time 5 "$url" >/dev/null 2>&1 && healthy=yes
    if [ "$state" = active ] && [ "$healthy" = yes ]; then return; fi
    echo "$(date -Iseconds) agent-vault degraded (state=$state health=$healthy) — restarting"
    systemctl restart "$svc"
    sleep 3
    healthy=no; curl -fsS --max-time 5 "$url" >/dev/null 2>&1 && healthy=yes
    if [ "$healthy" != yes ]; then
        send_alert "🔴 clem/$PROJECT agent-vault DOWN (state=$(systemctl is-active "$svc") health=$healthy) — brokered agents are failing auth"
    fi
}
`

const watchdogServiceTemplate = `[Unit]
Description=Clem watchdog for {{.Project}}

[Service]
Type=oneshot
ExecStart=/usr/local/bin/clem-watchdog-{{.Project}}.sh

[Install]
WantedBy=multi-user.target
`

const watchdogTimerTemplate = `[Unit]
Description=Clem watchdog timer for {{.Project}}

[Timer]
OnBootSec=5min
OnUnitActiveSec=5min
AccuracySec=30s

[Install]
WantedBy=timers.target
`

// staleMarginSeconds is added to an agent's iteration duration to derive the
// per-agent stale threshold passed to check_agent. Sized to comfortably exceed
// one watchdog tick (5 min) so a sleeping agent isn't restarted mid-cycle.
const staleMarginSeconds = 300

// staleFloorSeconds is the minimum stale threshold regardless of iteration
// duration. The runner log goes quiet for the whole claude session (the loop
// only logs at iteration boundaries), so a short-iteration agent must keep at
// least the historical 30-minute grace or healthy mid-task sessions get
// hard-restarted.
const staleFloorSeconds = 1800

type watchdogParams struct {
	Project        string
	AgentHomes     string
	EnvSource      string
	AlertChannel   string
	TokenEnvVar    string
	AlertCurl      string
	AgentChecks    string
	EgressCheckDef string
	EgressInvoke   string
	AuditLogPath   string
	VaultCheckDef  string
	VaultInvoke    string
}

// GenerateScript renders the watchdog shell script for the project.
func GenerateScript(cfg *config.Config) string {
	// Collect and sort agent keys for deterministic output
	keys := make([]string, 0, len(cfg.Agents))
	for key := range cfg.Agents {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	// Find orchestrator: prefer "lead", otherwise first alphabetically
	orchestratorUser := ""
	for _, key := range keys {
		if key == "lead" {
			orchestratorUser = cfg.OSUsername("lead")
			break
		}
	}
	if orchestratorUser == "" {
		orchestratorUser = cfg.OSUsername(keys[0])
	}

	envSource := fmt.Sprintf(`[ -f "/home/%s/.env" ] && source "/home/%s/.env"`, orchestratorUser, orchestratorUser)

	alertChannel := cfg.Coordination.Channels["alerts"]
	backend, _ := coordination.Known(cfg.Coordination.Backend) // validated at load time
	// $msg is the bash local set by send_alert; AlertTemplate expands it at
	// runtime so the curl body matches the per-backend wire format.
	alertCurl := fmt.Sprintf(backend.AlertTemplate, alertChannel, "$safe_msg")

	var checks strings.Builder
	for _, key := range keys {
		osUser := cfg.OSUsername(key)
		svc := cfg.ServiceName(key)
		ac := cfg.Agents[key]
		iterDur, _ := ac.IterationDuration() // validated at load time
		nightDur, _ := ac.IterationNightDuration()
		if nightDur > iterDur {
			// The stale threshold must cover the LONGEST configured sleep:
			// with iteration_night > iteration, sizing on the day value makes
			// every healthy night sleep look stale and hard-restarts the
			// agent all night.
			iterDur = nightDur
		}
		// Agents sleep up to iterDur between iterations; allow a 5-minute
		// margin so the next iteration's log line lands before we flag stale.
		stale := int(iterDur.Seconds()) + staleMarginSeconds
		if stale < staleFloorSeconds {
			stale = staleFloorSeconds
		}
		checks.WriteString(fmt.Sprintf(`check_agent "%s" "%s" "%s" "%d"`+"\n", key, osUser, svc, stale))
	}

	// Egress monitoring is wired in only when at least one agent is contained.
	egressDef, egressInvoke, auditPath := "", "", ""
	anyEgress := false
	for _, key := range keys {
		if cfg.EgressEnabledFor(key) {
			anyEgress = true
			break
		}
	}
	if anyEgress {
		auditPath = proxy.AuditLogFile(cfg.Project)
		// The main replacer is single-pass and will not re-scan injected text,
		// so substitute the audit path into the egress block up front.
		egressDef = strings.ReplaceAll(egressCheckDef, "{{.AuditLogPath}}", auditPath)
		egressInvoke = "check_egress\n"
	}

	// agent-vault health monitoring, wired in only when the backend is active.
	vaultDef, vaultInvoke := "", ""
	if cfg.Vault.IsAgentVault() {
		vaultDef = strings.NewReplacer(
			"{{.VaultService}}", cfg.AgentVaultServiceName(),
			"{{.VaultHealthURL}}", strings.TrimRight(cfg.Vault.AddrOrDefault(), "/")+"/health",
		).Replace(vaultCheckDef)
		vaultInvoke = "check_agent_vault\n"
	}

	p := watchdogParams{
		Project:        cfg.Project,
		EnvSource:      envSource,
		AlertChannel:   alertChannel,
		TokenEnvVar:    backend.TokenEnvVar,
		AlertCurl:      alertCurl,
		AgentChecks:    strings.TrimRight(checks.String(), "\n"),
		AgentHomes:     agentHomes(cfg, keys),
		EgressCheckDef: egressDef,
		EgressInvoke:   egressInvoke,
		AuditLogPath:   auditPath,
		VaultCheckDef:  vaultDef,
		VaultInvoke:    vaultInvoke,
	}

	r := strings.NewReplacer(
		"{{.Project}}", p.Project,
		"{{.EnvSource}}", p.EnvSource,
		"{{.AlertChannel}}", p.AlertChannel,
		"{{.TokenEnvVar}}", p.TokenEnvVar,
		"{{.AlertCurl}}", p.AlertCurl,
		"{{.AgentChecks}}", p.AgentChecks,
		"{{.AgentHomes}}", p.AgentHomes,
		"{{.EgressCheckDef}}", p.EgressCheckDef,
		"{{.EgressInvoke}}", p.EgressInvoke,
		"{{.AuditLogPath}}", p.AuditLogPath,
		"{{.VaultCheckDef}}", p.VaultCheckDef,
		"{{.VaultInvoke}}", p.VaultInvoke,
	)
	return r.Replace(watchdogScript)
}

// GenerateService renders the watchdog oneshot systemd service.
func GenerateService(cfg *config.Config) string {
	return strings.ReplaceAll(watchdogServiceTemplate, "{{.Project}}", cfg.Project)
}

// GenerateTimer renders the watchdog systemd timer.
func GenerateTimer(cfg *config.Config) string {
	return strings.ReplaceAll(watchdogTimerTemplate, "{{.Project}}", cfg.Project)
}

// agentHomes renders the space-separated list of agent home directories for
// the transcript-prune loop. Quoted paths are unnecessary: OS usernames are
// <project>-<agentkey>, both validated identifiers with no whitespace.
func agentHomes(cfg *config.Config, keys []string) string {
	homes := make([]string, 0, len(keys))
	for _, key := range keys {
		homes = append(homes, "/home/"+cfg.OSUsername(key))
	}
	return strings.Join(homes, " ")
}
