package watchdog

import (
	"fmt"
	"sort"
	"strings"

	"github.com/jahwag/clem/internal/config"
)

const watchdogScript = `#!/bin/bash
# clem-watchdog-{{.Project}}.sh — generated by clem provision
# Monitors agents for {{.Project}} and restarts dead sessions.

PROJECT="{{.Project}}"
COOLDOWN_DIR="/tmp/clem-watchdog-{{.Project}}"
COOLDOWN_SECONDS=300

mkdir -p "$COOLDOWN_DIR"

# Discord token sourced from orchestrator agent's .env
DISCORD_WEBHOOK=""
{{.EnvSource}}

send_alert() {
    local msg="$1"
    if [ -n "$DISCORD_TOKEN" ] && [ -n "{{.AlertChannel}}" ]; then
        local body
        body=$(python3 -c "import json,sys; print(json.dumps({'content':sys.argv[1]}))" "$msg")
        curl -s -X POST \
            "https://discord.com/api/v10/channels/{{.AlertChannel}}/messages" \
            -H "Authorization: Bot $DISCORD_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$body" > /dev/null 2>&1
    fi
    echo "$(date -Iseconds) ALERT: $msg"
}

check_agent() {
    local agent_key="$1"
    local os_user="$2"
    local service="$3"
    local cooldown_file="$COOLDOWN_DIR/${agent_key}.cooldown"

    # Check cooldown
    if [ -f "$cooldown_file" ]; then
        local last_alert
        last_alert=$(cat "$cooldown_file")
        local now
        now=$(date +%s)
        if (( now - last_alert < COOLDOWN_SECONDS )); then
            return
        fi
    fi

    local systemd_state
    systemd_state=$(systemctl show -p ActiveState --value "$service" 2>/dev/null)

    local tmux_alive="no"
    tmux has-session -t "$agent_key" 2>/dev/null && tmux_alive="yes"

    local fail_count_file="$COOLDOWN_DIR/${agent_key}.fails"

    # Case 1: systemd service dead — restart, then re-check. Only alert when
    # the restart did NOT bring the service back. Silences noise from
    # transient non-active states (e.g. ExecStop kill-session exit 1 during
    # a clean restart) that historically fired spurious "failed 3 times"
    # alerts even though auto-recovery had succeeded.
    if [ "$systemd_state" != "active" ]; then
        echo "$(date -Iseconds) $agent_key: systemd=$systemd_state — restarting"
        systemctl restart "$service"

        # systemctl restart returns after the job completes, but the forked
        # tmux daemon needs a beat to register its session.
        sleep 3
        local post_state post_tmux
        post_state=$(systemctl show -p ActiveState --value "$service" 2>/dev/null)
        post_tmux="no"
        tmux has-session -t "$agent_key" 2>/dev/null && post_tmux="yes"

        if [ "$post_state" = "active" ] && [ "$post_tmux" = "yes" ]; then
            # Restart succeeded — reset counter, suppress alert.
            echo 0 > "$fail_count_file"
            date +%s > "$cooldown_file"
            return
        fi

        local fails=$(( $(cat "$fail_count_file" 2>/dev/null || echo 0) + 1 ))
        echo "$fails" > "$fail_count_file"
        if (( fails >= 3 )); then
            send_alert "🔴 clem/$PROJECT: $agent_key failed $fails times consecutively (systemd=$post_state tmux=$post_tmux)"
            echo 0 > "$fail_count_file"
        fi
        date +%s > "$cooldown_file"
        return
    fi

    # Case 2: stale agent — runner log hasn't been updated in 30+ minutes
    local logfile="/home/${os_user}/.claude/${agent_key}-runner.log"
    if [ -f "$logfile" ]; then
        local log_age
        log_age=$(( $(date +%s) - $(stat -c %Y "$logfile") ))
        if (( log_age > 1800 )); then
            echo "$(date -Iseconds) $agent_key: stale for $((log_age/60))min — hard restarting"
            pkill -u "$os_user" -f claude || true
            sleep 2
            systemctl restart "$service"
            local fails=$(( $(cat "$fail_count_file" 2>/dev/null || echo 0) + 1 ))
            echo "$fails" > "$fail_count_file"
            if (( fails >= 3 )); then
                send_alert "🔴 clem/$PROJECT: $agent_key stale $fails times consecutively — may be rate-limited or broken"
                echo 0 > "$fail_count_file"
            fi
            date +%s > "$cooldown_file"
            return
        fi
    fi

    # Agent is healthy — reset fail counter
    [ -f "$fail_count_file" ] && echo 0 > "$fail_count_file"
}

check_oom() {
    local marker="$COOLDOWN_DIR/oom.last"
    local since
    if [ -f "$marker" ]; then
        since="@$(cat "$marker")"
    else
        since="5 minutes ago"
    fi
    date +%s > "$marker"

    local hits
    hits=$(journalctl --since "$since" --no-pager 2>/dev/null \
        | grep -E "killed by the OOM killer" \
        | grep -oE "clem-[a-zA-Z0-9_-]+\.service" \
        | sort | uniq -c | awk '{printf "%s x%s\n", $2, $1}')
    if [ -n "$hits" ]; then
        local mem
        mem=$(free -h | awk '/^Mem:/ {printf "%s/%s", $3, $2} /^Swap:/ {printf " swap=%s/%s", $3, $2}')
        send_alert "🔥 clem/$PROJECT OOM-kill detected (last 5min): $hits — RAM $mem"
    fi
}

{{.AgentChecks}}

check_oom
`

const watchdogServiceTemplate = `[Unit]
Description=Clem watchdog for {{.Project}}

[Service]
Type=oneshot
ExecStart=/usr/local/bin/clem-watchdog-{{.Project}}.sh

[Install]
WantedBy=multi-user.target
`

const watchdogTimerTemplate = `[Unit]
Description=Clem watchdog timer for {{.Project}}

[Timer]
OnBootSec=5min
OnUnitActiveSec=5min
AccuracySec=30s

[Install]
WantedBy=timers.target
`

type watchdogParams struct {
	Project      string
	EnvSource    string
	AlertChannel string
	AgentChecks  string
}

// GenerateScript renders the watchdog shell script for the project.
func GenerateScript(cfg *config.Config) string {
	// Collect and sort agent keys for deterministic output
	keys := make([]string, 0, len(cfg.Agents))
	for key := range cfg.Agents {
		keys = append(keys, key)
	}
	sort.Strings(keys)

	// Find orchestrator: prefer "lead", otherwise first alphabetically
	orchestratorUser := ""
	for _, key := range keys {
		if key == "lead" {
			orchestratorUser = cfg.OSUsername("lead")
			break
		}
	}
	if orchestratorUser == "" {
		orchestratorUser = cfg.OSUsername(keys[0])
	}

	envSource := fmt.Sprintf(`[ -f "/home/%s/.env" ] && source "/home/%s/.env"`, orchestratorUser, orchestratorUser)

	alertChannel := cfg.Coordination.Channels["alerts"]

	var checks strings.Builder
	for _, key := range keys {
		osUser := cfg.OSUsername(key)
		svc := cfg.ServiceName(key)
		checks.WriteString(fmt.Sprintf(`check_agent "%s" "%s" "%s"`+"\n", key, osUser, svc))
	}

	p := watchdogParams{
		Project:      cfg.Project,
		EnvSource:    envSource,
		AlertChannel: alertChannel,
		AgentChecks:  strings.TrimRight(checks.String(), "\n"),
	}

	r := strings.NewReplacer(
		"{{.Project}}", p.Project,
		"{{.EnvSource}}", p.EnvSource,
		"{{.AlertChannel}}", p.AlertChannel,
		"{{.AgentChecks}}", p.AgentChecks,
	)
	return r.Replace(watchdogScript)
}

// GenerateService renders the watchdog oneshot systemd service.
func GenerateService(cfg *config.Config) string {
	return strings.ReplaceAll(watchdogServiceTemplate, "{{.Project}}", cfg.Project)
}

// GenerateTimer renders the watchdog systemd timer.
func GenerateTimer(cfg *config.Config) string {
	return strings.ReplaceAll(watchdogTimerTemplate, "{{.Project}}", cfg.Project)
}
