// Package proxy generates the on-disk artifacts for clem's egress containment:
// the pipelock forward-proxy config + systemd service, and a per-agent nftables
// UID firewall + its systemd loader. clem writes these at provision time; at
// runtime clem is not in the loop.
//
// Containment model (see the migration plan): a single pipelock instance runs
// as a dedicated non-login system user on loopback. A root-owned nftables
// `output` chain rejects all egress for each agent UID except to the proxy
// (and any explicitly-allowed loopback ports), so a compromised agent cannot
// reach the network except through pipelock — the kernel UID firewall is the
// boundary, not the cooperative HTTPS_PROXY env var.
package proxy

import (
	"fmt"
	"net"
	"os/user"
	"sort"
	"strconv"
	"strings"

	"github.com/jahwag/clem/internal/config"
)

// AuditLogPath is the signed JSONL audit log pipelock writes; the watchdog
// tails it for block/DLP events.
const AuditLogPath = "/var/log/clem"

// userUIDLookup resolves an OS username to its numeric UID. Replaced in tests
// via package-level assignment (same pattern as runner.userHomeLookup).
var userUIDLookup = func(username string) (int, error) {
	u, err := user.Lookup(username)
	if err != nil {
		return 0, fmt.Errorf("user %q not found: %w", username, err)
	}
	uid, err := strconv.Atoi(u.Uid)
	if err != nil {
		return 0, fmt.Errorf("parsing uid for %q: %w", username, err)
	}
	return uid, nil
}

// PipelockConfigPath returns the path to a project's pipelock.yaml.
func PipelockConfigPath(project string) string {
	return fmt.Sprintf("/etc/clem/pipelock-%s.yaml", project)
}

// NftablesPath returns the path to a project's nftables ruleset file.
func NftablesPath(project string) string {
	return fmt.Sprintf("/etc/clem/clem-egress-%s.nft", project)
}

// AuditLogFile returns the pipelock audit log path for a project.
func AuditLogFile(project string) string {
	return fmt.Sprintf("%s/pipelock-%s-audit.jsonl", AuditLogPath, project)
}

// nftTableName returns the nftables table identifier for a project. nft
// identifiers disallow hyphens, so they are mapped to underscores.
func nftTableName(project string) string {
	return "clem_egress_" + strings.ReplaceAll(project, "-", "_")
}

// GeneratePipelockConfig renders pipelock.yaml for a project. Phase 1 is
// CONNECT-only (tls_interception off) so no CA distribution is needed; the
// forward proxy still enforces the api_allowlist by SNI/CONNECT host and writes
// the signed audit log. Verified config keys per pipelock v2.5.x.
func GeneratePipelockConfig(cfg *config.Config) string {
	e := cfg.Egress
	var b strings.Builder
	b.WriteString("# Generated by clem provision — do not edit by hand.\n")
	b.WriteString("version: 1\n")
	fmt.Fprintf(&b, "mode: %s\n", e.PostureOrDefault())
	b.WriteString("enforce: true\n")
	b.WriteString("fetch_proxy:\n")
	fmt.Fprintf(&b, "  listen: \"127.0.0.1:%d\"\n", e.ProxyPortOrDefault())
	b.WriteString("forward_proxy:\n")
	// forward_proxy.enabled is restart-required (not hot-reloadable).
	b.WriteString("  enabled: true\n")
	b.WriteString("  sni_verification: true\n")
	b.WriteString("tls_interception:\n")
	fmt.Fprintf(&b, "  enabled: %t\n", e.TLSIntercept)
	b.WriteString("api_allowlist:\n")
	for _, d := range e.DomainsOrDefault() {
		fmt.Fprintf(&b, "  - %q\n", d)
	}
	b.WriteString("logging:\n")
	b.WriteString("  format: json\n")
	b.WriteString("  output: file\n")
	fmt.Fprintf(&b, "  file: %s\n", AuditLogFile(cfg.Project))
	b.WriteString("  include_allowed: true\n")
	b.WriteString("  include_blocked: true\n")
	return b.String()
}

const pipelockServiceTemplate = `[Unit]
Description=clem egress proxy (pipelock) for {{.Project}}
After=network-online.target {{.NftablesService}}
Wants=network-online.target

[Service]
Type=simple
User={{.ProxyUser}}
ExecStart=/usr/local/bin/pipelock run --config {{.ConfigPath}} --listen 127.0.0.1:{{.ProxyPort}}
ExecReload=/bin/kill -HUP $MAINPID
Restart=always
RestartSec=2
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths={{.LogDir}}
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
`

// GeneratePipelockService renders the systemd unit that runs the pipelock
// forward proxy as the dedicated egress system user.
func GeneratePipelockService(cfg *config.Config) string {
	r := strings.NewReplacer(
		"{{.Project}}", cfg.Project,
		"{{.ProxyUser}}", cfg.Egress.ProxyUserOrDefault(),
		"{{.ConfigPath}}", PipelockConfigPath(cfg.Project),
		"{{.ProxyPort}}", strconv.Itoa(cfg.Egress.ProxyPortOrDefault()),
		"{{.LogDir}}", AuditLogPath,
		"{{.NftablesService}}", cfg.NftablesServiceName(),
	)
	return r.Replace(pipelockServiceTemplate)
}

const nftablesServiceTemplate = `[Unit]
Description=clem egress firewall (nftables) for {{.Project}}
After=nftables.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/nft -f {{.NftPath}}

[Install]
WantedBy=multi-user.target
`

// GenerateNftablesService renders the oneshot systemd unit that applies the
// egress firewall ruleset on boot (before agent units, which order After it).
func GenerateNftablesService(cfg *config.Config) string {
	r := strings.NewReplacer(
		"{{.Project}}", cfg.Project,
		"{{.NftPath}}", NftablesPath(cfg.Project),
	)
	return r.Replace(nftablesServiceTemplate)
}

// AgentVaultEnvFile is the root-owned file holding agent-vault's master
// password, loaded by the systemd unit via EnvironmentFile (agent-vault has no
// systemd-credential support). Never readable by agent users.
const AgentVaultEnvFile = "/etc/clem/agent-vault.env"

// AgentVaultDataDir is the agent-vault encrypted store, owned by the vault user.
const AgentVaultDataDir = "/var/lib/clem-vault"

const agentVaultServiceTemplate = `[Unit]
Description=clem credential proxy (agent-vault) for {{.Project}}
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User={{.VaultUser}}
# agent-vault has no data-dir flag; its encrypted store lives at $HOME/.agent-vault.
# Point HOME at the dedicated data dir so the store lands under ReadWritePaths.
Environment=HOME={{.DataDir}}
EnvironmentFile={{.EnvFile}}
ExecStart=/usr/local/bin/agent-vault server --port {{.MgmtPort}} --mitm-port {{.MitmPort}}
Restart=always
RestartSec=2
NoNewPrivileges=yes
ProtectSystem=strict
ProtectHome=yes
ReadWritePaths={{.DataDir}}
PrivateTmp=yes

[Install]
WantedBy=multi-user.target
`

// GenerateAgentVaultService renders the systemd unit running the agent-vault
// credential proxy as the dedicated vault system user. The master password is
// supplied via a root-owned EnvironmentFile (agent-vault reads
// AGENT_VAULT_MASTER_PASSWORD from env; it has no systemd-credential support).
func GenerateAgentVaultService(cfg *config.Config) string {
	addr := cfg.Vault.AddrOrDefault()
	mgmtPort := portOf(addr, "14321")
	mitmPort := portOf(cfg.Vault.ProxyHostOrDefault(), "14322")
	r := strings.NewReplacer(
		"{{.Project}}", cfg.Project,
		"{{.VaultUser}}", cfg.Vault.SystemUserOrDefault(),
		"{{.EnvFile}}", AgentVaultEnvFile,
		"{{.DataDir}}", AgentVaultDataDir,
		"{{.MgmtPort}}", mgmtPort,
		"{{.MitmPort}}", mitmPort,
	)
	return r.Replace(agentVaultServiceTemplate)
}

// portOf extracts the port from a host:port or scheme://host:port string
// (IPv6-safe via net.SplitHostPort), falling back to def.
func portOf(s, def string) string {
	s = strings.TrimRight(strings.TrimPrefix(strings.TrimPrefix(s, "https://"), "http://"), "/")
	if _, port, err := net.SplitHostPort(s); err == nil && port != "" {
		return port
	}
	return def
}

// agentVaultPort returns the numeric loopback port agents reach agent-vault's
// MITM proxy on, or 0 if the agent-vault backend is not active.
func agentVaultPort(cfg *config.Config) int {
	if !cfg.Vault.IsAgentVault() {
		return 0
	}
	n, err := strconv.Atoi(portOf(cfg.Vault.ProxyHostOrDefault(), "14322"))
	if err != nil {
		return 14322
	}
	return n
}

// GenerateNftables renders the per-agent UID egress firewall for a project.
// Each egress-enabled agent's UID is rejected for all traffic except loopback
// to the proxy port (and any AllowLocalhostPorts); the proxy user egresses
// freely. The default-accept policy leaves all other users (root, services)
// untouched. Idempotent reload: ensure-then-delete-then-create the table.
func GenerateNftables(cfg *config.Config) (string, error) {
	proxyUID, err := userUIDLookup(cfg.Egress.ProxyUserOrDefault())
	if err != nil {
		return "", fmt.Errorf("resolving egress proxy user: %w", err)
	}

	// Base allowed loopback destination ports: pipelock proxy + extras.
	basePorts := []int{cfg.Egress.ProxyPortOrDefault()}
	basePorts = append(basePorts, cfg.Egress.AllowLocalhostPorts...)
	avPort := agentVaultPort(cfg) // 0 unless agent-vault backend active

	// portListFor returns the deduped, sorted "p1, p2" loopback port set for an
	// agent: the base ports, plus agent-vault's MITM port for brokered agents
	// (their HTTPS_PROXY points at agent-vault, not pipelock).
	portListFor := func(ac config.AgentConfig) string {
		set := map[int]struct{}{}
		for _, p := range basePorts {
			set[p] = struct{}{}
		}
		if avPort > 0 && ac.VaultBroker {
			set[avPort] = struct{}{}
		}
		ports := make([]int, 0, len(set))
		for p := range set {
			ports = append(ports, p)
		}
		sort.Ints(ports)
		strs := make([]string, len(ports))
		for i, p := range ports {
			strs[i] = strconv.Itoa(p)
		}
		return strings.Join(strs, ", ")
	}

	// Collect contained agent UIDs, sorted for deterministic output.
	keys := make([]string, 0, len(cfg.Agents))
	for k := range cfg.Agents {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	type agentUID struct {
		key string
		uid int
	}
	var agents []agentUID
	for _, k := range keys {
		if !cfg.EgressEnabledFor(k) {
			continue
		}
		uid, err := userUIDLookup(cfg.OSUsername(k))
		if err != nil {
			return "", fmt.Errorf("resolving agent %s: %w", k, err)
		}
		agents = append(agents, agentUID{k, uid})
	}

	table := nftTableName(cfg.Project)
	var b strings.Builder
	b.WriteString("#!/usr/sbin/nft -f\n")
	b.WriteString("# Generated by clem provision — egress containment for " + cfg.Project + ".\n")
	b.WriteString("# Rejects all egress for each agent UID except loopback to the pipelock proxy.\n")
	// Idempotent reload idiom: create-if-absent, delete, recreate.
	fmt.Fprintf(&b, "table inet %s { }\n", table)
	fmt.Fprintf(&b, "delete table inet %s\n", table)
	fmt.Fprintf(&b, "table inet %s {\n", table)
	b.WriteString("\tchain output {\n")
	b.WriteString("\t\ttype filter hook output priority 0; policy accept;\n")
	fmt.Fprintf(&b, "\t\t# %s runs the proxy and egresses freely\n", cfg.Egress.ProxyUserOrDefault())
	fmt.Fprintf(&b, "\t\tmeta skuid %d accept\n", proxyUID)
	for _, a := range agents {
		ac := cfg.Agents[a.key]
		fmt.Fprintf(&b, "\t\t# agent %s (%s)\n", a.key, cfg.OSUsername(a.key))
		// ttyd web-terminal replies are inbound-initiated, so their outbound
		// packets must be allowed — but ONLY from the ttyd source port. A blanket
		// `ct state established` allow would let a compromised agent run a bind
		// or reverse shell and exfiltrate over an attacker-initiated connection,
		// defeating containment. Scope it to the ttyd port; agents with no web
		// terminal get no established-state allowance at all. (The proxy path
		// needs none: outbound packets to the proxy always match the dport rule.)
		if ac.WebTerminalPort > 0 {
			fmt.Fprintf(&b, "\t\tmeta skuid %d tcp sport %d ct state established,related accept\n", a.uid, ac.WebTerminalPort)
		}
		portList := portListFor(ac)
		fmt.Fprintf(&b, "\t\tmeta skuid %d ip daddr 127.0.0.1 tcp dport { %s } accept\n", a.uid, portList)
		fmt.Fprintf(&b, "\t\tmeta skuid %d ip6 daddr ::1 tcp dport { %s } accept\n", a.uid, portList)
		fmt.Fprintf(&b, "\t\tmeta skuid %d reject with icmpx type admin-prohibited\n", a.uid)
	}
	b.WriteString("\t}\n")
	b.WriteString("}\n")
	return b.String(), nil
}
