package githubwatch

import (
	"fmt"
	"net/url"
	"strings"

	"github.com/jahwag/clem/internal/config"
)

const (
	defaultPollSeconds     = 60
	defaultDebounceSeconds = 5
)

const watchScriptTemplate = `#!/bin/bash
# clem-github-watch-{{.Project}}-{{.AgentKey}}.sh — generated by clem provision
# Polls GitHub Issues for new claimable tasks and wakes the agent tmux session.

REPO="{{.GithubRepo}}"
LABEL="{{.TaskLabel}}"
LABEL_ENC="{{.TaskLabelEncoded}}"
AGENT_KEY="{{.AgentKey}}"
POLL_INTERVAL={{.PollSeconds}}
DEBOUNCE={{.DebounceSeconds}}
STATE_FILE="$HOME/.claude/github-watch.state"
LOGFILE="$HOME/.claude/{{.AgentKey}}-github-watch.log"

mkdir -p "$HOME/.claude"
[ -f "$HOME/.env" ] && source "$HOME/.env"
{{.ProxyExport}}

log() { echo "$(date -Iseconds) $1" | tee -a "$LOGFILE"; }

load_state() {
    ETAG=""
    OLD_IDS=""
    HAD_STATE_FILE=0
    if [ -f "$STATE_FILE" ]; then
        HAD_STATE_FILE=1
        ETAG=$(grep '^etag=' "$STATE_FILE" 2>/dev/null | cut -d= -f2- || true)
        OLD_IDS=$(grep '^ids=' "$STATE_FILE" 2>/dev/null | cut -d= -f2- || true)
    fi
}

save_state() {
    local last_wake_line=""
    [ -f "$STATE_FILE" ] && last_wake_line=$(grep '^last_wake=' "$STATE_FILE" 2>/dev/null || true)
    {
        printf 'etag=%s\nids=%s\n' "$ETAG" "$NEW_IDS"
        [ -n "$last_wake_line" ] && echo "$last_wake_line"
    } > "$STATE_FILE"
}

maybe_wake() {
    local now last
    now=$(date +%s)
    last=0
    [ -f "$STATE_FILE" ] && last=$(grep '^last_wake=' "$STATE_FILE" 2>/dev/null | cut -d= -f2 || echo 0)
    if (( now - last < DEBOUNCE )); then
        return
    fi
    if tmux has-session -t "$AGENT_KEY" 2>/dev/null; then
        tmux send-keys -t "$AGENT_KEY" "" Enter
        log "woke tmux session $AGENT_KEY (new claimable issues)"
    fi
    if grep -q '^last_wake=' "$STATE_FILE" 2>/dev/null; then
        sed -i "s/^last_wake=.*/last_wake=$now/" "$STATE_FILE"
    else
        echo "last_wake=$now" >> "$STATE_FILE"
    fi
}

poll_once() {
    if [ -z "$GH_TOKEN" ]; then
        log "GH_TOKEN unset — skipping poll"
        return
    fi
    load_state
    local hdr body code new_etag
    hdr=$(mktemp)
    body=$(mktemp)
    trap 'rm -f "$hdr" "$body"' RETURN
    local -a curl_args=(
        -sS -D "$hdr" -o "$body" -w '%{http_code}'
        -H "Authorization: Bearer $GH_TOKEN"
        -H "Accept: application/vnd.github+json"
    )
    [ -n "$ETAG" ] && curl_args+=(-H "If-None-Match: $ETAG")
    code=$(curl "${curl_args[@]}" \
        "https://api.github.com/repos/${REPO}/issues?labels=${LABEL_ENC}&state=open&per_page=30")
    if [ "$code" = "304" ]; then
        return
    fi
    if [ "$code" != "200" ]; then
        log "GitHub API returned HTTP $code"
        return
    fi
    new_etag=$(grep -i '^etag:' "$hdr" | tail -1 | sed 's/^[Ee][Tt][Aa][Gg]:[[:space:]]*//;s/\r$//')
    NEW_IDS=$(python3 -c "
import json,sys
try:
    data=json.load(open(sys.argv[1]))
except Exception:
    sys.exit(0)
nums=sorted(i['number'] for i in data if isinstance(i,dict) and not i.get('assignees'))
print(' '.join(str(n) for n in nums))
" "$body" 2>/dev/null || true)
    ETAG="$new_etag"
    # Skip wake on the very first poll (no prior state). Once a state file exists,
    # diff even when OLD_IDS is empty so empty→non-empty transitions wake the agent.
    if [ "$HAD_STATE_FILE" -eq 1 ]; then
        if comm -13 <(echo "$OLD_IDS" | tr ' ' '\n' | LC_ALL=C sort) <(echo "$NEW_IDS" | tr ' ' '\n' | LC_ALL=C sort) | grep -q .; then
            maybe_wake
        fi
    fi
    save_state
}

log "starting GitHub issue watcher for $REPO label=$LABEL poll=${POLL_INTERVAL}s"
while true; do
    poll_once
    sleep "$POLL_INTERVAL"
done
`

const serviceTemplate = `[Unit]
Description=Clem GitHub issue watcher: {{.AgentName}} ({{.Project}})
After=clem-{{.Project}}-{{.AgentKey}}.service
{{.ProxyUnitDeps}}BindsTo=clem-{{.Project}}-{{.AgentKey}}.service
PartOf=clem-{{.Project}}-{{.AgentKey}}.service
JoinsNamespaceOf=clem-{{.Project}}-{{.AgentKey}}.service

[Service]
Type=simple
User={{.OSUser}}
PrivateTmp=yes
ExecStart={{.HomeDir}}/.local/bin/clem-github-watch.sh
Restart=on-failure
RestartSec=10
{{.EgressDirectives}}
[Install]
WantedBy=multi-user.target
`

type params struct {
	Project          string
	AgentKey         string
	AgentName        string
	OSUser           string
	HomeDir          string
	GithubRepo       string
	TaskLabel        string
	TaskLabelEncoded string
	PollSeconds      int
	DebounceSeconds  int
	ProxyExport      string
	ProxyUnitDeps    string
	EgressDirectives string
}

// GenerateScript renders the per-agent GitHub issue watcher script.
func GenerateScript(cfg *config.Config, agentKey string) string {
	ac := cfg.Agents[agentKey]
	taskLabel := cfg.Coordination.Channels["tasks"]
	if taskLabel == "" {
		taskLabel = "clem:todo"
	}
	p := params{
		Project:          cfg.Project,
		AgentKey:         agentKey,
		AgentName:        ac.Name,
		OSUser:           cfg.OSUsername(agentKey),
		HomeDir:          fmt.Sprintf("/home/%s", cfg.OSUsername(agentKey)),
		GithubRepo:       cfg.Coordination.GithubRepo,
		TaskLabel:        taskLabel,
		TaskLabelEncoded: url.QueryEscape(taskLabel),
		PollSeconds:      defaultPollSeconds,
		DebounceSeconds:  defaultDebounceSeconds,
		ProxyExport:      proxyExportBlock(cfg, agentKey),
		EgressDirectives: egressDirectives(cfg, agentKey),
	}
	return render(watchScriptTemplate, p)
}

// GenerateService renders the systemd unit for the GitHub issue watcher sidecar.
func GenerateService(cfg *config.Config, agentKey string) string {
	ac := cfg.Agents[agentKey]
	p := params{
		Project:          cfg.Project,
		AgentKey:         agentKey,
		AgentName:        ac.Name,
		OSUser:           cfg.OSUsername(agentKey),
		HomeDir:          fmt.Sprintf("/home/%s", cfg.OSUsername(agentKey)),
		ProxyUnitDeps:    proxyUnitDeps(cfg, agentKey),
		EgressDirectives: egressDirectives(cfg, agentKey),
	}
	return render(serviceTemplate, p)
}

// proxyExportBlock is retained as a seam but emits nothing. Egress containment
// now requires vault_broker, and the watcher sources $HOME/.env (above this
// block in the template), which already carries the authenticated agent-vault
// HTTPS_PROXY written by agent.BrokeredEnv. Emitting a plain http:// export here
// would clobber that correct value with a credential-less one.
func proxyExportBlock(cfg *config.Config, agentKey string) string {
	return ""
}

const egressDirectivesBlock = `# Same loopback-only egress guard as the agent service.
IPAddressDeny=any
IPAddressAllow=127.0.0.0/8
IPAddressAllow=::1/128
`

func egressDirectives(cfg *config.Config, agentKey string) string {
	if cfg.EgressEnabledFor(agentKey) {
		return egressDirectivesBlock
	}
	return ""
}

// proxyUnitDeps ties the watcher to the agent-vault proxy when egress
// containment is active for the agent, so polls do not fail open against a down
// proxy.
func proxyUnitDeps(cfg *config.Config, agentKey string) string {
	if !cfg.EgressEnabledFor(agentKey) {
		return ""
	}
	return fmt.Sprintf("After=%s\nWants=%s\n",
		cfg.AgentVaultServiceName(), cfg.AgentVaultServiceName())
}

func render(tmpl string, p params) string {
	r := strings.NewReplacer(
		"{{.Project}}", p.Project,
		"{{.AgentKey}}", p.AgentKey,
		"{{.AgentName}}", p.AgentName,
		"{{.OSUser}}", p.OSUser,
		"{{.HomeDir}}", p.HomeDir,
		"{{.GithubRepo}}", p.GithubRepo,
		"{{.TaskLabel}}", p.TaskLabel,
		"{{.TaskLabelEncoded}}", p.TaskLabelEncoded,
		"{{.PollSeconds}}", fmt.Sprintf("%d", p.PollSeconds),
		"{{.DebounceSeconds}}", fmt.Sprintf("%d", p.DebounceSeconds),
		"{{.ProxyExport}}", p.ProxyExport,
		"{{.ProxyUnitDeps}}", p.ProxyUnitDeps,
		"{{.EgressDirectives}}", p.EgressDirectives,
	)
	return r.Replace(tmpl)
}
